default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails-react-go-fish_development

test:
  <<: *default
  database: rails-react-go-fish-rails_test
